name: CI - Build and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Run tests with JaCoCo coverage
        run: mvn clean test jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" \
              -d '{"content": "✅ Build finalizado com sucesso!"}' \
              ${{ secrets.DISCORD_WEBHOOK }}
        continue-on-error: true
