name: "🚀 Deploy JavaDoc to GitHub Pages"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: 📆 Gerar JavaDoc
        run: mvn javadoc:javadoc

      - name: 🚀 Publicar em GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
          publish_branch: gh-pages
